# Generated by Django 5.1 on 2024-09-05 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_project_delete_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_quoted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('png1', models.ImageField(upload_to='tenders/')),
                ('png2', models.ImageField(upload_to='tenders/')),
                ('png3', models.ImageField(upload_to='tenders/')),
                ('png4', models.ImageField(upload_to='tenders/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
