# Generated by Django 5.1 on 2024-09-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='agency',
            field=models.CharField(default=12, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
