# Generated by Django 5.1 on 2024-09-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_customuser_address_customuser_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agency',
            field=models.CharField(max_length=250),
        ),
    ]
