# Generated by Django 5.1 on 2024-09-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_customuser_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='png4',
        ),
        migrations.AddField(
            model_name='tender',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='tenders/'),
        ),
    ]
