# Generated by Django 5.1 on 2024-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_tender_png4_tender_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='min_quote',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=10),
            preserve_default=False,
        ),
    ]
